apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack-galera-network-isolation
spec:
  secret: osp-secret
  storageClass: local-storage
  #tls:
  #  endpoint:
  #    internal:
  #      enabled: false
  #    public:
  #      enabled: true
  dns:
    template:
      override:
        service:
          metadata:
            annotations:
              metallb.universe.tf/address-pool: ctlplane
              metallb.universe.tf/allow-shared-ip: ctlplane
              metallb.universe.tf/loadBalancerIPs: 192.168.122.80
          spec:
            type: LoadBalancer
      options:
      - key: server
        values:
        - 192.168.122.1
      replicas: 1
  cinder:
    enabled: false
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      secret: osp-secret
      cinderAPI:
        replicas: 0
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      cinderScheduler:
        replicas: 0
      cinderBackup:
        networkAttachments:
        - storage
        replicas: 0 # backend needs to be configured
      cinderVolumes:
        volume1:
          networkAttachments:
          - storage
          replicas: 0 # backend needs to be configured
  glance:
    enabled: false # for adoption testing
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      storageClass: ""
      storageRequest: 1G
      glanceAPIInternal:
        replicas: 1
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
        networkAttachments:
        - storage
      glanceAPIExternal:
        replicas: 0
        networkAttachments:
        - storage
  keystone:
    enabled: false # for adoption testing
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    enabled: false
    templates:
      openstack:
        storageRequest: 500M
      openstack-cell1:
        storageRequest: 500M
  galera:
    enabled: true
    templates:
      openstack:
        storageRequest: 500M
        secret: osp-secret
        replicas: 1
      openstack-cell1:
        storageRequest: 500M
        secret: osp-secret
        replicas: 1
  memcached:
    templates:
      memcached:
        replicas: 1
  neutron:
    enabled: false # for adoption testing
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
      networkAttachments:
      - internalapi
  horizon:
    enabled: false
    apiOverride:
      route: {}
    template:
      replicas: 0
      secret: osp-secret
  nova:
    enabled: false # for adoption testing
    apiOverride:
      route: {}
    template:
      # This creates a collapsed cell deployment same as what OSP17 does by
      # default. The conductor in cell1 acts as both the cell conductor and the
      # super conductor hence cell0 conductor is disabled. Also in this
      # deployment both the top level services and cell1 service will share the
      # same message bus and database service instance so there is no cell
      # separation implemented.
      cellTemplates:
          cell0:
            cellDatabaseUser: nova_cell0
            noVNCProxyServiceTemplate:
              replicas: 0 # must remain 0?
            metadataServiceTemplate:
              replicas: 0 # must remain 0?
            conductorServiceTemplate:
              replicas: 0 # must remain 0
            externalEndpoints:
            - endpoint: internal
              ipAddressPool: internalapi
              loadBalancerIPs:
              - 172.17.0.80
            hasAPIAccess: true
          cell1:
            cellDatabaseUser: nova_cell1
            cellDatabaseInstance: openstack-cell1
            cellMessageBusInstance: rabbitmq-cell1
            noVNCProxyServiceTemplate:
              replicas: 0 #1, to be started locally
            metadataServiceTemplate:
              replicas: 0 #1, to be started locally
            conductorServiceTemplate:
              replicas: 0 #1, to be started locally
            hasAPIAccess: true
            externalEndpoints:
            - endpoint: internal
              ipAddressPool: internalapi
              loadBalancerIPs:
              - 172.17.0.80
      apiServiceTemplate:
        replicas: 0 #1, to be started locally
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      metadataServiceTemplate:
        replicas: 0 #1, to be started locally
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      schedulerServiceTemplate:
        replicas: 0 #1, to be started locally
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      noVNCProxyServiceTemplate:
        replicas: 0 #1, to be started locally, or just for cell1?
        # FIXME(bogdando): not needed for VNCservice?
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  manila:
    enabled: false
    apiOverride:
      route: {}
    template:
      manilaAPI:
        replicas: 0
        networkAttachments:
        - internalapi
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      manilaScheduler:
        replicas: 0
        networkAttachments:
        - internalapi
      manilaShares:
        share1:
          replicas: 0
          networkAttachments:
          - storage
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 1
          dbType: NB
          storageRequest: 1G
          networkAttachment: internalapi
        ovndbcluster-sb:
          replicas: 1
          dbType: SB
          storageRequest: 1G
          networkAttachment: internalapi
      ovnNorthd:
        replicas: 1
        networkAttachment: internalapi
      ovnController:
        replicas: 1
        external-ids:
          system-id: "random"
          ovn-bridge: "br-int"
          ovn-encap-type: "geneve"
        networkAttachment: tenant
  placement:
    enabled: false # for adoption testing
    apiOverride:
      route: {}
    template:
      replicas: 0 # for adoption testing
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 1
        resources:
          requests:
            cpu: 150m
            memory: 250Mi
          limits:
            cpu: 300m
            memory: 500Mi
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
      rabbitmq-cell1:
        replicas: 1
        resources:
          requests:
            cpu: 150m
            memory: 250Mi
          limits:
            cpu: 300m
            memory: 500Mi
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
  heat:
    apiOverride:
      route: {}
    cnfAPIOverride:
      route: {}
    enabled: false
    template:
      databaseInstance: openstack
      heatAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 0
      heatEngine:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 0
      heatCfnAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 0
      secret: osp-secret
  ironic:
    enabled: false
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 0
      ironicConductors:
      - replicas: 0
        storageRequest: 1G
      ironicInspector:
        replicas: 0
      ironicNeutronAgent:
        replicas: 0
      secret: osp-secret
  ceilometer:
    enabled: false
    template:
      passwordSelector:
        service: CeilometerPassword
      secret: osp-secret
      serviceUser: ceilometer
  swift:
    enabled: false
    proxyOverride:
      route: {}
    template:
      swiftRing:
        ringReplicas: 1 # can't be 0
      swiftStorage:
        replicas: 1 # can't be 0
      swiftProxy:
        replicas: 1 # can't be 0
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
  octavia:
    enabled: false
    template:
      databaseInstance: openstack
      octaviaAPI:
        replicas: 0
      secret: osp-secret
  redis:
    enabled: false
